### ISSUE TITLE
Change JSON file path to sync w/git... 

### ISSUE THREAD

**Issue by amygroshek** [holman/boom#112]
I found the config var in `storage.rb` that sets the `JSON_FILE = "#{ENV['HOME']}/.boom"`. I'd like to change this up, to `JSON_FILE = "#{ENV['HOME']}/.boom/.boom"`, to get those snippets into a git repo and sync across my diff machines. What will I break? Immediately? On upgrade?

**Comment by holman** [comment]
It *probably* won't break anything... probably. :)

Typically, though, our advice is to just make `~/.boom` a symlink, and from there you can toss it anywhere you'd like. I think in this case it doesn't really matter at all, though.

Give a shout if something's weird, though. :)

**Comment by amygroshek** [comment]
Right. Symlink. Way better idea. Thanks. Pfffft.
